### ISSUE TITLE
代码细节问题（部分）

### ISSUE THREAD

**Issue by LeaFrock** [jiangzf93/Blog#1]
[这里](https://github.com/jiangzf93/Blog/blob/master/Blog/Models/SeedData.cs#L17)应该用Count()吗？Any()是不是更适合？同时从逻辑严谨性来说，是否应该分别判断和初始化数据？

[首页Index](https://github.com/jiangzf93/Blog/blob/master/Blog/Controllers/HomeController.cs#L20)是最常被调用的方法，这里数据通过EF Core只会执行读取操作。可以再优化性能吗？请参考官方文档：[跟踪与不跟踪](https://docs.microsoft.com/zh-cn/ef/core/querying/tracking)。另外，这里为什么不写成异步呢？

[这里](https://github.com/jiangzf93/Blog/blob/master/Blog/Controllers/ManageController.cs#L109)这样写会发生什么？它是上面106行代码重复，放在这里会发生什么？

**Comment by jiangzf93** [comment]
回复第三项：代码重复会导致重复查询数据库，造成性能下降，已按照建议修改；
回复第一项：按照建议，已修改为当Authors表为空时执行初始化（为防止首页显示异常，对IsHost属性为True的这个Author设置为无法删除，而Articles这个表是可空的，因此仅将判断Authors是否为空作为判断是否初始化的条件）

**Comment by jiangzf93** [comment]
> [这里](https://github.com/jiangzf93/Blog/blob/master/Blog/Models/SeedData.cs#L17)应该用Count()吗？Any()是不是更适合？同时从逻辑严谨性来说，是否应该分别判断和初始化数据？
> **按照建议，已修改为当Authors表为空时执行初始化（为防止首页显示异常，对IsHost属性为True的这个Author设置为无法删除，而Articles这个表是可空的，因此仅将判断Authors是否为空作为判断是否初始化的条件）**
> [首页Index](https://github.com/jiangzf93/Blog/blob/master/Blog/Controllers/HomeController.cs#L20)是最常被调用的方法，这里数据通过EF Core只会执行读取操作。可以再优化性能吗？请参考官方文档：[跟踪与不跟踪](https://docs.microsoft.com/zh-cn/ef/core/querying/tracking)。另外，这里为什么不写成异步呢？
> 
> [这里](https://github.com/jiangzf93/Blog/blob/master/Blog/Controllers/ManageController.cs#L109)这样写会发生什么？它是上面106行代码重复，放在这里会发生什么？
>**代码重复会导致重复查询数据库，造成性能下降，已按照建议修改；**
